<?php

namespace ContainerFdTYNtU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EQzPXhtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eQzPXht' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eQzPXht'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'filesystem' => ['privates', 'filesystem', 'getFilesystemService', true],
            'typeFichierRepository' => ['privates', 'App\\Repository\\Ged\\TypeFichierRepository', 'getTypeFichierRepositoryService', true],
        ], [
            'filesystem' => '?',
            'typeFichierRepository' => 'App\\Repository\\Ged\\TypeFichierRepository',
        ]);
    }
}
