<?php

namespace ContainerFdTYNtU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JETyMYoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JETyMYo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JETyMYo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'interlocuteur' => ['privates', '.errored..service_locator.JETyMYo.App\\Entity\\Interlocuteur\\Interlocuteur', NULL, 'Cannot autowire service ".service_locator.JETyMYo": it references class "App\\Entity\\Interlocuteur\\Interlocuteur" but no such service exists.'],
        ], [
            'interlocuteur' => 'App\\Entity\\Interlocuteur\\Interlocuteur',
        ]);
    }
}
