<?php

namespace ContainerFdTYNtU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J5Fyh42Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J5Fyh42' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.J5Fyh42'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'interlocuteurRepository' => ['privates', 'App\\Repository\\Interlocuteur\\InterlocuteurRepository', 'getInterlocuteurRepositoryService', true],
        ], [
            'interlocuteurRepository' => 'App\\Repository\\Interlocuteur\\InterlocuteurRepository',
        ]);
    }
}
