<?php

namespace ContainerFdTYNtU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CfV6_N0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CfV6.n0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CfV6.n0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'interlocuteur' => ['privates', '.errored..service_locator.CfV6.n0.App\\Entity\\Interlocuteur\\Interlocuteur', NULL, 'Cannot autowire service ".service_locator.CfV6.n0": it references class "App\\Entity\\Interlocuteur\\Interlocuteur" but no such service exists.'],
            'interlocuteurRepository' => ['privates', 'App\\Repository\\Interlocuteur\\InterlocuteurRepository', 'getInterlocuteurRepositoryService', true],
        ], [
            'interlocuteur' => 'App\\Entity\\Interlocuteur\\Interlocuteur',
            'interlocuteurRepository' => 'App\\Repository\\Interlocuteur\\InterlocuteurRepository',
        ]);
    }
}
