<?php

namespace ContainerFdTYNtU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NEXLZ4wService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nEXLZ4w' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nEXLZ4w'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sousEntite' => ['privates', '.errored..service_locator.nEXLZ4w.App\\Entity\\Entite\\SousEntite', NULL, 'Cannot autowire service ".service_locator.nEXLZ4w": it references class "App\\Entity\\Entite\\SousEntite" but no such service exists.'],
        ], [
            'sousEntite' => 'App\\Entity\\Entite\\SousEntite',
        ]);
    }
}
