<?php

namespace ContainerFdTYNtU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OciXra0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OciXra0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OciXra0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'depot' => ['privates', '.errored..service_locator.OciXra0.App\\Entity\\Entite\\Depot', NULL, 'Cannot autowire service ".service_locator.OciXra0": it references class "App\\Entity\\Entite\\Depot" but no such service exists.'],
            'depotRepository' => ['privates', 'App\\Repository\\Entite\\DepotRepository', 'getDepotRepositoryService', true],
        ], [
            'depot' => 'App\\Entity\\Entite\\Depot',
            'depotRepository' => 'App\\Repository\\Entite\\DepotRepository',
        ]);
    }
}
