<?php

namespace ContainerFdTYNtU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AMQBrDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aMQBr_D' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aMQBr_D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'depotRepository' => ['privates', 'App\\Repository\\Entite\\DepotRepository', 'getDepotRepositoryService', true],
        ], [
            'depotRepository' => 'App\\Repository\\Entite\\DepotRepository',
        ]);
    }
}
