<?php

namespace ContainerFdTYNtU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFichierTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Ged\FichierType' shared autowired service.
     *
     * @return \App\Form\Ged\FichierType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Ged/FichierType.php';

        return $container->privates['App\\Form\\Ged\\FichierType'] = new \App\Form\Ged\FichierType();
    }
}
