<?php

namespace ContainerFdTYNtU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInterlocuteurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.CfV6.n0.App\Entity\Interlocuteur\Interlocuteur' shared service.
     *
     * @return \App\Entity\Interlocuteur\Interlocuteur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.CfV6.n0": it references class "App\\Entity\\Interlocuteur\\Interlocuteur" but no such service exists.');
    }
}
