<?php

namespace ContainerFdTYNtU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSousEntiteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nEXLZ4w.App\Entity\Entite\SousEntite' shared service.
     *
     * @return \App\Entity\Entite\SousEntite
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.nEXLZ4w": it references class "App\\Entity\\Entite\\SousEntite" but no such service exists.');
    }
}
