<?php

namespace ContainerFdTYNtU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getService2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.q263N.H.App\Entity\User\Service' shared service.
     *
     * @return \App\Entity\User\Service
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.q263N.H": it references class "App\\Entity\\User\\Service" but no such service exists.');
    }
}
