<?php

namespace ContainerFdTYNtU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeFichier2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.oibSTqW.App\Entity\Ged\TypeFichier' shared service.
     *
     * @return \App\Entity\Ged\TypeFichier
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.oibSTqW": it references class "App\\Entity\\Ged\\TypeFichier" but no such service exists.');
    }
}
