<?php

namespace Container93psNC5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R7pFJZ4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.r7pFJZ4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.r7pFJZ4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sousEntite' => ['privates', '.errored..service_locator.r7pFJZ4.App\\Entity\\Entite\\SousEntite', NULL, 'Cannot autowire service ".service_locator.r7pFJZ4": it references class "App\\Entity\\Entite\\SousEntite" but no such service exists.'],
            'sousEntiteRepository' => ['privates', 'App\\Repository\\Entite\\SousEntiteRepository', 'getSousEntiteRepositoryService', true],
        ], [
            'sousEntite' => 'App\\Entity\\Entite\\SousEntite',
            'sousEntiteRepository' => 'App\\Repository\\Entite\\SousEntiteRepository',
        ]);
    }
}
