<?php

namespace Container93psNC5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SQ8C4LbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sQ8C4Lb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sQ8C4Lb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typeFichier' => ['privates', '.errored..service_locator.sQ8C4Lb.App\\Entity\\Ged\\TypeFichier', NULL, 'Cannot autowire service ".service_locator.sQ8C4Lb": it references class "App\\Entity\\Ged\\TypeFichier" but no such service exists.'],
        ], [
            'typeFichier' => 'App\\Entity\\Ged\\TypeFichier',
        ]);
    }
}
