<?php

namespace Container93psNC5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Cvb0ntdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Cvb0ntd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Cvb0ntd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entite' => ['privates', '.errored..service_locator.Cvb0ntd.App\\Entity\\Entite\\Entite', NULL, 'Cannot autowire service ".service_locator.Cvb0ntd": it references class "App\\Entity\\Entite\\Entite" but no such service exists.'],
        ], [
            'entite' => 'App\\Entity\\Entite\\Entite',
        ]);
    }
}
