<?php

namespace Container93psNC5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q263N_HService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q263N.H' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q263N.H'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'service' => ['privates', '.errored..service_locator.q263N.H.App\\Entity\\User\\Service', NULL, 'Cannot autowire service ".service_locator.q263N.H": it references class "App\\Entity\\User\\Service" but no such service exists.'],
            'serviceRepository' => ['privates', 'App\\Repository\\User\\ServiceRepository', 'getServiceRepositoryService', true],
        ], [
            'service' => 'App\\Entity\\User\\Service',
            'serviceRepository' => 'App\\Repository\\User\\ServiceRepository',
        ]);
    }
}
