<?php

namespace Container93psNC5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8t_LZXBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8t.LZXB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8t.LZXB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'poste' => ['privates', '.errored..service_locator.8t.LZXB.App\\Entity\\User\\Poste', NULL, 'Cannot autowire service ".service_locator.8t.LZXB": it references class "App\\Entity\\User\\Poste" but no such service exists.'],
            'posteRepository' => ['privates', 'App\\Repository\\User\\PosteRepository', 'getPosteRepositoryService', true],
        ], [
            'poste' => 'App\\Entity\\User\\Poste',
            'posteRepository' => 'App\\Repository\\User\\PosteRepository',
        ]);
    }
}
