<?php

namespace Container93psNC5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Oz01I9PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Oz01I9P' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Oz01I9P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fichierRepository' => ['privates', 'App\\Repository\\Ged\\FichierRepository', 'getFichierRepositoryService', true],
        ], [
            'fichierRepository' => 'App\\Repository\\Ged\\FichierRepository',
        ]);
    }
}
