<?php

namespace Container93psNC5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepotControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Entite\DepotController' shared autowired service.
     *
     * @return \App\Controller\Entite\DepotController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Entite/DepotController.php';

        $container->services['App\\Controller\\Entite\\DepotController'] = $instance = new \App\Controller\Entite\DepotController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\Entite\\DepotController', $container));

        return $instance;
    }
}
