<?php

namespace Container93psNC5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntite2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Yi74xVt.App\Entity\Entite\Entite' shared service.
     *
     * @return \App\Entity\Entite\Entite
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Yi74xVt": it references class "App\\Entity\\Entite\\Entite" but no such service exists.');
    }
}
