<?php

namespace Container93psNC5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFichier2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gZohkbE.App\Entity\Ged\Fichier' shared service.
     *
     * @return \App\Entity\Ged\Fichier
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.gZohkbE": it references class "App\\Entity\\Ged\\Fichier" but no such service exists.');
    }
}
