<?php

namespace App\Entity\Depot;

use App\Repository\Depot\ChauffeursRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ChauffeursRepository::class)]

class Chauffeurs
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'bigint')]
    private $idchauffeur;

    #[ORM\Column(type: 'integer')]

    private $idtransporteur;

    #[ORM\Column(type: 'string')]
    private $nom;

    #[ORM\Column(type: 'string')]
    private $prenom;

    #[ORM\Column(type: 'string')]
    private $portable;

    #[ORM\Column(type: 'string')]
    private $email;

    #[ORM\Column(type: 'boolean')]
    private $actif;
    public function getIdchauffeur(): ?int
    {
        return $this->idchauffeur;
    }

    // Note: There is no setter for $idchauffeur as it is autogenerated.

    // Getter and Setter for $idtransporteur
    public function getIdtransporteur(): ?int
    {
        return $this->idtransporteur;
    }

    public function setIdtransporteur(int $idtransporteur): self
    {
        $this->idtransporteur = $idtransporteur;
        return $this;
    }

    // Getter and Setter for $nom
    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;
        return $this;
    }

    // Getter and Setter for $prenom
    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;
        return $this;
    }

    // Getter and Setter for $portable
    public function getPortable(): ?string
    {
        return $this->portable;
    }

    public function setPortable(string $portable): self
    {
        $this->portable = $portable;
        return $this;
    }

    // Getter and Setter for $email
    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;
        return $this;
    }

    // Getter and Setter for $actif
    public function isActif(): bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;
        return $this;
    }
}
