<?php

namespace Proxies\__CG__\App\Entity\Interlocuteur;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Personne extends \App\Entity\Interlocuteur\Personne implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Interlocuteur\\Personne' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Interlocuteur\\Personne' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Interlocuteur\\Personne' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Interlocuteur\\Personne' . "\0" . 'interlocuteur', '' . "\0" . 'App\\Entity\\Interlocuteur\\Personne' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Interlocuteur\\Personne' . "\0" . 'adresse1', '' . "\0" . 'App\\Entity\\Interlocuteur\\Personne' . "\0" . 'adresse2', '' . "\0" . 'App\\Entity\\Interlocuteur\\Personne' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Interlocuteur\\Personne' . "\0" . 'codePostal', '' . "\0" . 'App\\Entity\\Interlocuteur\\Personne' . "\0" . 'pays'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Interlocuteur\\Personne' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Interlocuteur\\Personne' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Interlocuteur\\Personne' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Interlocuteur\\Personne' . "\0" . 'interlocuteur', '' . "\0" . 'App\\Entity\\Interlocuteur\\Personne' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Interlocuteur\\Personne' . "\0" . 'adresse1', '' . "\0" . 'App\\Entity\\Interlocuteur\\Personne' . "\0" . 'adresse2', '' . "\0" . 'App\\Entity\\Interlocuteur\\Personne' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Interlocuteur\\Personne' . "\0" . 'codePostal', '' . "\0" . 'App\\Entity\\Interlocuteur\\Personne' . "\0" . 'pays'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Personne $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Interlocuteur\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\Interlocuteur\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterlocuteur(): ?\App\Entity\Interlocuteur\Interlocuteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterlocuteur', []);

        return parent::getInterlocuteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setInterlocuteur(?\App\Entity\Interlocuteur\Interlocuteur $interlocuteur): \App\Entity\Interlocuteur\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterlocuteur', [$interlocuteur]);

        return parent::setInterlocuteur($interlocuteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom(string $prenom): \App\Entity\Interlocuteur\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse1(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse1', []);

        return parent::getAdresse1();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse1(string $adresse1): \App\Entity\Interlocuteur\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse1', [$adresse1]);

        return parent::setAdresse1($adresse1);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse2', []);

        return parent::getAdresse2();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse2(string $adresse2): \App\Entity\Interlocuteur\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse2', [$adresse2]);

        return parent::setAdresse2($adresse2);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille(string $ville): \App\Entity\Interlocuteur\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$ville]);

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostal(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostal', []);

        return parent::getCodePostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostal(string $codePostal): \App\Entity\Interlocuteur\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostal', [$codePostal]);

        return parent::setCodePostal($codePostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getPays(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPays', []);

        return parent::getPays();
    }

    /**
     * {@inheritDoc}
     */
    public function setPays(string $pays): \App\Entity\Interlocuteur\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPays', [$pays]);

        return parent::setPays($pays);
    }

}
