<?php

namespace ContainerVFBJlOr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LhOtlXMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lhOtlXM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lhOtlXM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'serviceRepository' => ['privates', 'App\\Repository\\User\\ServiceRepository', 'getServiceRepositoryService', true],
        ], [
            'serviceRepository' => 'App\\Repository\\User\\ServiceRepository',
        ]);
    }
}
