<?php

namespace ContainerVFBJlOr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_InCL3XKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.InCL3XK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.InCL3XK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'poste' => ['privates', '.errored..service_locator.InCL3XK.App\\Entity\\User\\Poste', NULL, 'Cannot autowire service ".service_locator.InCL3XK": it references class "App\\Entity\\User\\Poste" but no such service exists.'],
        ], [
            'poste' => 'App\\Entity\\User\\Poste',
        ]);
    }
}
