<?php

namespace ContainerVFBJlOr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W0BvQfYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.W0BvQfY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.W0BvQfY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'depot' => ['privates', '.errored..service_locator.W0BvQfY.App\\Entity\\Entite\\Depot', NULL, 'Cannot autowire service ".service_locator.W0BvQfY": it references class "App\\Entity\\Entite\\Depot" but no such service exists.'],
        ], [
            'depot' => 'App\\Entity\\Entite\\Depot',
        ]);
    }
}
