<?php

namespace ContainerVFBJlOr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XySZXYvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xySZXYv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xySZXYv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'posteRepository' => ['privates', 'App\\Repository\\User\\PosteRepository', 'getPosteRepositoryService', true],
        ], [
            'posteRepository' => 'App\\Repository\\User\\PosteRepository',
        ]);
    }
}
