<?php

namespace ContainerVFBJlOr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yi74xVtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Yi74xVt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Yi74xVt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entite' => ['privates', '.errored..service_locator.Yi74xVt.App\\Entity\\Entite\\Entite', NULL, 'Cannot autowire service ".service_locator.Yi74xVt": it references class "App\\Entity\\Entite\\Entite" but no such service exists.'],
            'entiteRepository' => ['privates', 'App\\Repository\\Entite\\EntiteRepository', 'getEntiteRepositoryService', true],
        ], [
            'entite' => 'App\\Entity\\Entite\\Entite',
            'entiteRepository' => 'App\\Repository\\Entite\\EntiteRepository',
        ]);
    }
}
