<?php

namespace ContainerVFBJlOr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepotService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.OciXra0.App\Entity\Entite\Depot' shared service.
     *
     * @return \App\Entity\Entite\Depot
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.OciXra0": it references class "App\\Entity\\Entite\\Depot" but no such service exists.');
    }
}
