<?php

namespace ContainerVFBJlOr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPosteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8t.LZXB.App\Entity\User\Poste' shared service.
     *
     * @return \App\Entity\User\Poste
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8t.LZXB": it references class "App\\Entity\\User\\Poste" but no such service exists.');
    }
}
