<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVFBJlOr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVFBJlOr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVFBJlOr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVFBJlOr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVFBJlOr\App_KernelDevDebugContainer([
    'container.build_hash' => 'VFBJlOr',
    'container.build_id' => 'ffea9ecd',
    'container.build_time' => 1651399039,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVFBJlOr');
