<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container93psNC5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container93psNC5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container93psNC5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container93psNC5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container93psNC5\App_KernelDevDebugContainer([
    'container.build_hash' => '93psNC5',
    'container.build_id' => 'cd086870',
    'container.build_time' => 1651513184,
], __DIR__.\DIRECTORY_SEPARATOR.'Container93psNC5');
