<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.9a71ee5d.js',
                '/build/95.2ee15dd7.js',
                '/build/app.6837fdec.js',
            ],
            'css' => [
                '/build/95.1d776be7.css',
                '/build/app.227bb562.css',
            ],
        ],
        'chart' => [
            'js' => [
                '/build/runtime.9a71ee5d.js',
                '/build/403.d255a224.js',
                '/build/chart.158157e3.js',
            ],
        ],
    ],
],

]];
